function DataTest() {
  const dataTest = [
    {
      commandNumber: 1,
      date: "2023-05-09",
      totalAmount: 97,
      status: "En cours",
      customer: {
        lastNameCustomer: "Brumbye",
        firstNameCustomer: "Alexandrina",
      },
      articles: {
        name: "Intelsat S.A.",
        price: 94,
        qrCode: "54868-0846",
        numberOfArticles: 4,
      },
      deliverer: { lastNameDeliverer: "Asmus", firstNameDeliverer: "Sibella" },
      address: {
        street: "42 Evergreen Point",
        streetNumber: "711",
        postalCode: "7823",
        city: "Ath",
        country: "Belgium",
      },
      is_checked: false,
    },
    {
      commandNumber: 2,
      date: "2024-01-24",
      totalAmount: 57,
      status: "Terminé",
      customer: { lastNameCustomer: "Perrelli", firstNameCustomer: "Carlee" },
      articles: {
        name: "Colony NorthStar, Inc.",
        price: 12,
        qrCode: "62654-144",
        numberOfArticles: 3,
      },
      deliverer: { lastNameDeliverer: "O'Neill", firstNameDeliverer: "Bennie" },
      address: {
        street: "242 Steensland Way",
        streetNumber: "18785",
        postalCode: "9052",
        city: "Gent",
        country: "Belgium",
      },
      is_checked: false,
    },
    {
      commandNumber: 3,
      date: "2023-07-17",
      totalAmount: 73,
      status: "Terminé",
      customer: { lastNameCustomer: "Dunnaway", firstNameCustomer: "Carmine" },
      articles: {
        name: "Select Comfort Corporation",
        price: 58,
        qrCode: "10424-154",
        numberOfArticles: 3,
      },
      deliverer: {
        lastNameDeliverer: "Hopfer",
        firstNameDeliverer: "Wadsworth",
      },
      address: {
        street: "13 Tomscot Point",
        streetNumber: "7037",
        postalCode: "1170",
        city: "Bruxelles",
        country: "Belgium",
      },
      is_checked: false,
    },
    {
      commandNumber: 4,
      date: "2023-04-17",
      totalAmount: 42,
      status: "Terminé",
      customer: { lastNameCustomer: "Cowe", firstNameCustomer: "Brenna" },
      articles: {
        name: "Mesa Royalty Trust",
        price: 34,
        qrCode: "63517-016",
        numberOfArticles: 5,
      },
      deliverer: { lastNameDeliverer: "Murrison", firstNameDeliverer: "Essa" },
      address: {
        street: "2364 Vidon Hill",
        streetNumber: "568",
        postalCode: "6594",
        city: "Momignies",
        country: "Belgium",
      },
      is_checked: false,
    },
    {
      commandNumber: 5,
      date: "2023-09-14",
      totalAmount: 53,
      status: "Terminé",
      customer: { lastNameCustomer: "Kershaw", firstNameCustomer: "Caspar" },
      articles: {
        name: "Horizon Bancorp (IN)",
        price: 35,
        qrCode: "37205-750",
        numberOfArticles: 2,
      },
      deliverer: {
        lastNameDeliverer: "Kempshall",
        firstNameDeliverer: "Timothee",
      },
      address: {
        street: "7 Texas Junction",
        streetNumber: "4",
        postalCode: "6834",
        city: "Bouillon",
        country: "Belgium",
      },
      is_checked: false,
    },
    {
      commandNumber: 6,
      date: "2023-11-21",
      totalAmount: 88,
      status: "Terminé",
      customer: { lastNameCustomer: "Vyse", firstNameCustomer: "Car" },
      articles: {
        name: "AptarGroup, Inc.",
        price: 84,
        qrCode: "0143-9668",
        numberOfArticles: 4,
      },
      deliverer: { lastNameDeliverer: "Janczyk", firstNameDeliverer: "Livvie" },
      address: {
        street: "43662 Crowley Place",
        streetNumber: "86",
        postalCode: "2170",
        city: "Antwerpen",
        country: "Belgium",
      },
      is_checked: false,
    },
    {
      commandNumber: 7,
      date: "2023-11-27",
      totalAmount: 12,
      status: "Terminé",
      customer: { lastNameCustomer: "Leyland", firstNameCustomer: "Gabie" },
      articles: {
        name: "Arrow Electronics, Inc.",
        price: 94,
        qrCode: "10542-012",
        numberOfArticles: 3,
      },
      deliverer: {
        lastNameDeliverer: "Dowthwaite",
        firstNameDeliverer: "Lalo",
      },
      address: {
        street: "3338 Browning Plaza",
        streetNumber: "89283",
        postalCode: "7823",
        city: "Ath",
        country: "Belgium",
      },
      is_checked: false,
    },
    {
      commandNumber: 8,
      date: "2024-02-24",
      totalAmount: 77,
      status: "Terminé",
      customer: { lastNameCustomer: "Renton", firstNameCustomer: "Kerrin" },
      articles: {
        name: "Garmin Ltd.",
        price: 8,
        qrCode: "57844-112",
        numberOfArticles: 1,
      },
      deliverer: { lastNameDeliverer: "Unwin", firstNameDeliverer: "Suellen" },
      address: {
        street: "42028 Shelley Crossing",
        streetNumber: "0",
        postalCode: "2170",
        city: "Antwerpen",
        country: "Belgium",
      },
      is_checked: false,
    },
    {
      commandNumber: 9,
      date: "2023-07-30",
      totalAmount: 60,
      status: "Terminé",
      customer: { lastNameCustomer: "Jeaves", firstNameCustomer: "Trumann" },
      articles: {
        name: "Santander Consumer USA Holdings Inc.",
        price: 94,
        qrCode: "62584-639",
        numberOfArticles: 2,
      },
      deliverer: { lastNameDeliverer: "Bolsover", firstNameDeliverer: "Ravid" },
      address: {
        street: "56 Golf Course Crossing",
        streetNumber: "059",
        postalCode: "1050",
        city: "Bruxelles",
        country: "Belgium",
      },
      is_checked: false,
    },
    {
      commandNumber: 10,
      date: "2023-12-30",
      totalAmount: 13,
      status: "Terminé",
      customer: { lastNameCustomer: "Reaper", firstNameCustomer: "Dawna" },
      articles: {
        name: "John Wiley & Sons, Inc.",
        price: 90,
        qrCode: "49693-1701",
        numberOfArticles: 5,
      },
      deliverer: { lastNameDeliverer: "Woolger", firstNameDeliverer: "Marijo" },
      address: {
        street: "576 Atwood Point",
        streetNumber: "8899",
        postalCode: "5100",
        city: "Namur",
        country: "Belgium",
      },
      is_checked: false,
    },
    {
      commandNumber: 11,
      date: "2023-12-08",
      totalAmount: 84,
      status: "Terminé",
      customer: { lastNameCustomer: "Najera", firstNameCustomer: "Romola" },
      articles: {
        name: "PowerShares LadderRite 0-5 Year Corporate Bond Portfolio",
        price: 64,
        qrCode: "11673-910",
        numberOfArticles: 3,
      },
      deliverer: { lastNameDeliverer: "Peasey", firstNameDeliverer: "Ally" },
      address: {
        street: "07 North Way",
        streetNumber: "35",
        postalCode: "5100",
        city: "Namur",
        country: "Belgium",
      },
      is_checked: false,
    },
    {
      commandNumber: 12,
      date: "2023-08-16",
      totalAmount: 49,
      status: "Terminé",
      customer: { lastNameCustomer: "Bernt", firstNameCustomer: "Dewie" },
      articles: {
        name: "Sotherly Hotels Inc.",
        price: 20,
        qrCode: "65862-028",
        numberOfArticles: 2,
      },
      deliverer: { lastNameDeliverer: "Espasa", firstNameDeliverer: "Emylee" },
      address: {
        street: "3 Randy },address: {street",
        streetNumber: "7594",
        postalCode: "2170",
        city: "Antwerpen",
        country: "Belgium",
      },
      is_checked: false,
    },
    {
      commandNumber: 13,
      date: "2023-06-29",
      totalAmount: 82,
      status: "Terminé",
      customer: { lastNameCustomer: "Cottier", firstNameCustomer: "Christos" },
      articles: {
        name: "Scudder Global High Income Fund, Inc.",
        price: 87,
        qrCode: "68196-484",
        numberOfArticles: 3,
      },
      deliverer: {
        lastNameDeliverer: "Durrell",
        firstNameDeliverer: "Murdock",
      },
      address: {
        street: "434 Oak Trail",
        streetNumber: "1",
        postalCode: "7604",
        city: "Péruwelz",
        country: "Belgium",
      },
      is_checked: false,
    },
    {
      commandNumber: 14,
      date: "2023-05-12",
      totalAmount: 1,
      status: "Terminé",
      customer: { lastNameCustomer: "Rignold", firstNameCustomer: "Fred" },
      articles: {
        name: "America Movil, S.A.B. de C.V.",
        price: 51,
        qrCode: "43857-0336",
        numberOfArticles: 5,
      },
      deliverer: {
        lastNameDeliverer: "Durban",
        firstNameDeliverer: "Brandais",
      },
      address: {
        street: "8039 Hollow Ridge Trail",
        streetNumber: "20271",
        postalCode: "7032",
        city: "Mons",
        country: "Belgium",
      },
      is_checked: false,
    },
    {
      commandNumber: 15,
      date: "2024-03-13",
      totalAmount: 38,
      status: "Terminé",
      customer: {
        lastNameCustomer: "Middlemiss",
        firstNameCustomer: "Garrott",
      },
      articles: {
        name: "AgroFresh Solutions, Inc.",
        price: 73,
        qrCode: "0409-4178",
        numberOfArticles: 1,
      },
      deliverer: { lastNameDeliverer: "Fryers", firstNameDeliverer: "Rosene" },
      address: {
        street: "2 Blackbird Park",
        streetNumber: "501",
        postalCode: "9404",
        city: "Ninove",
        country: "Belgium",
      },
      is_checked: false,
    },
    {
      commandNumber: 16,
      date: "2023-06-02",
      totalAmount: 75,
      status: "Terminé",
      customer: { lastNameCustomer: "Donovan", firstNameCustomer: "Pearl" },
      articles: {
        name: "Piedmont Office Realty Trust, Inc.",
        price: 63,
        qrCode: "0268-0940",
        numberOfArticles: 3,
      },
      deliverer: { lastNameDeliverer: "Nock", firstNameDeliverer: "Heida" },
      address: {
        street: "23 Garrison Circle",
        streetNumber: "7",
        postalCode: "6594",
        city: "Momignies",
        country: "Belgium",
      },
      is_checked: false,
    },
    {
      commandNumber: 17,
      date: "2023-11-30",
      totalAmount: 55,
      status: "Terminé",
      customer: { lastNameCustomer: "Brickner", firstNameCustomer: "Wes" },
      articles: {
        name: "Cohen & Steers Limited Duration Preferred and Income Fund, Inc",
        price: 87,
        qrCode: "72036-001",
        numberOfArticles: 2,
      },
      deliverer: { lastNameDeliverer: "Bazely", firstNameDeliverer: "Auberon" },
      address: {
        street: "2771 Crowley },address: {street",
        streetNumber: "8157",
        postalCode: "2170",
        city: "Antwerpen",
        country: "Belgium",
      },
      is_checked: false,
    },
    {
      commandNumber: 18,
      date: "2023-09-22",
      totalAmount: 14,
      status: "Terminé",
      customer: { lastNameCustomer: "Lait", firstNameCustomer: "Sophi" },
      articles: {
        name: "LINE Corporation",
        price: 59,
        qrCode: "49349-247",
        numberOfArticles: 3,
      },
      deliverer: { lastNameDeliverer: "Brettel", firstNameDeliverer: "Devin" },
      address: {
        street: "66 Ridgeview Court",
        streetNumber: "54",
        postalCode: "9052",
        city: "Gent",
        country: "Belgium",
      },
      is_checked: false,
    },
    {
      commandNumber: 19,
      date: "2023-08-28",
      totalAmount: 43,
      status: "Terminé",
      customer: { lastNameCustomer: "Merriton", firstNameCustomer: "Arliene" },
      articles: {
        name: "TechTarget, Inc.",
        price: 3,
        qrCode: "65954-042",
        numberOfArticles: 1,
      },
      deliverer: { lastNameDeliverer: "Anchor", firstNameDeliverer: "Tybi" },
      address: {
        street: "8835 Kedzie Junction",
        streetNumber: "695",
        postalCode: "5100",
        city: "Namur",
        country: "Belgium",
      },
      is_checked: false,
    },
    {
      commandNumber: 20,
      date: "2023-04-18",
      totalAmount: 28,
      status: "Terminé",
      customer: { lastNameCustomer: "Jiggle", firstNameCustomer: "Franciska" },
      articles: {
        name: "Packaging Corporation of America",
        price: 5,
        qrCode: "49035-236",
        numberOfArticles: 3,
      },
      deliverer: { lastNameDeliverer: "Tobin", firstNameDeliverer: "Karlotta" },
      address: {
        street: "375 Jana Place",
        streetNumber: "9",
        postalCode: "6042",
        city: "Charleroi",
        country: "Belgium",
      },
      is_checked: false,
    },
    {
      commandNumber: 21,
      date: "2023-09-12",
      totalAmount: 69,
      status: "Terminé",
      customer: { lastNameCustomer: "Flemmich", firstNameCustomer: "Darius" },
      articles: {
        name: "VelocityShares Daily 2x VIX Short-Term ETN",
        price: 97,
        qrCode: "24385-541",
        numberOfArticles: 2,
      },
      deliverer: {
        lastNameDeliverer: "Chaldecott",
        firstNameDeliverer: "Rosalyn",
      },
      address: {
        street: "36420 Linden Center",
        streetNumber: "503",
        postalCode: "7823",
        city: "Ath",
        country: "Belgium",
      },
      is_checked: false,
    },
    {
      commandNumber: 22,
      date: "2024-03-17",
      totalAmount: 8,
      status: "Terminé",
      customer: { lastNameCustomer: "Rodolphe", firstNameCustomer: "Tildy" },
      articles: {
        name: "Vermillion, Inc.",
        price: 66,
        qrCode: "64679-947",
        numberOfArticles: 5,
      },
      deliverer: {
        lastNameDeliverer: "Willatt",
        firstNameDeliverer: "Giavani",
      },
      address: {
        street: "14426 Chinook Point",
        streetNumber: "348",
        postalCode: "9052",
        city: "Gent",
        country: "Belgium",
      },
      is_checked: false,
    },
    {
      commandNumber: 23,
      date: "2023-12-16",
      totalAmount: 36,
      status: "Terminé",
      customer: { lastNameCustomer: "Balmforth", firstNameCustomer: "Doralin" },
      articles: {
        name: "Barracuda Networks, Inc.",
        price: 83,
        qrCode: "65044-1081",
        numberOfArticles: 5,
      },
      deliverer: {
        lastNameDeliverer: "Hallowell",
        firstNameDeliverer: "Haydon",
      },
      address: {
        street: "80271 Brentwood Plaza",
        streetNumber: "824",
        postalCode: "7032",
        city: "Mons",
        country: "Belgium",
      },
      is_checked: false,
    },
    {
      commandNumber: 24,
      date: "2023-04-17",
      totalAmount: 61,
      status: "Terminé",
      customer: { lastNameCustomer: "Philpault", firstNameCustomer: "Vivi" },
      articles: {
        name: "BlackRock Investment Quality Municipal Trust Inc. (The)",
        price: 47,
        qrCode: "57664-391",
        numberOfArticles: 4,
      },
      deliverer: { lastNameDeliverer: "Shimony", firstNameDeliverer: "Lavina" },
      address: {
        street: "5913 Memorial Plaza",
        streetNumber: "3",
        postalCode: "7536",
        city: "Tournai",
        country: "Belgium",
      },
      is_checked: false,
    },
    {
      commandNumber: 25,
      date: "2024-02-03",
      totalAmount: 99,
      status: "Terminé",
      customer: { lastNameCustomer: "Eddowis", firstNameCustomer: "Andie" },
      articles: {
        name: "PRA Group, Inc.",
        price: 33,
        qrCode: "43772-0039",
        numberOfArticles: 1,
      },
      deliverer: {
        lastNameDeliverer: "Edgeworth",
        firstNameDeliverer: "Ruthann",
      },
      address: {
        street: "7 New Castle Trail",
        streetNumber: "5",
        postalCode: "9052",
        city: "Gent",
        country: "Belgium",
      },
      is_checked: false,
    },
    {
      commandNumber: 26,
      date: "2023-12-17",
      totalAmount: 55,
      status: "Terminé",
      customer: {
        lastNameCustomer: "Phizacklea",
        firstNameCustomer: "Wilbert",
      },
      articles: {
        name: "Ryder System, Inc.",
        price: 3,
        qrCode: "55154-2537",
        numberOfArticles: 3,
      },
      deliverer: { lastNameDeliverer: "Cowins", firstNameDeliverer: "Minerva" },
      address: {
        street: "64851 Moland Parkway",
        streetNumber: "12",
        postalCode: "7504",
        city: "Tournai",
        country: "Belgium",
      },
      is_checked: false,
    },
    {
      commandNumber: 27,
      date: "2023-04-25",
      totalAmount: 4,
      status: "Terminé",
      customer: {
        lastNameCustomer: "Limeburn",
        firstNameCustomer: "Martguerita",
      },
      articles: {
        name: "ContraFect Corporation",
        price: 29,
        qrCode: "0143-1202",
        numberOfArticles: 3,
      },
      deliverer: {
        lastNameDeliverer: "Gooderson",
        firstNameDeliverer: "Robbie",
      },
      address: {
        street: "769 Blackbird Trail",
        streetNumber: "15681",
        postalCode: "7032",
        city: "Mons",
        country: "Belgium",
      },
      is_checked: false,
    },
    {
      commandNumber: 28,
      date: "2024-03-20",
      totalAmount: 88,
      status: "Terminé",
      customer: { lastNameCustomer: "Ridewood", firstNameCustomer: "Porter" },
      articles: {
        name: "Deutsche Bank AG",
        price: 50,
        qrCode: "54569-2148",
        numberOfArticles: 3,
      },
      deliverer: {
        lastNameDeliverer: "Sprakes",
        firstNameDeliverer: "Guthrey",
      },
      address: {
        street: "1920 Waywood Parkway",
        streetNumber: "396",
        postalCode: "7032",
        city: "Mons",
        country: "Belgium",
      },
      is_checked: false,
    },
    {
      commandNumber: 29,
      date: "2023-08-29",
      totalAmount: 16,
      status: "Terminé",
      customer: { lastNameCustomer: "Hinrich", firstNameCustomer: "Janessa" },
      articles: {
        name: "Banco Latinoamericano de Comercio Exterior, S.A.",
        price: 36,
        qrCode: "63736-948",
        numberOfArticles: 5,
      },
      deliverer: { lastNameDeliverer: "Coldwell", firstNameDeliverer: "Emmie" },
      address: {
        street: "47877 Holmberg Alley",
        streetNumber: "8",
        postalCode: "9404",
        city: "Ninove",
        country: "Belgium",
      },
      is_checked: false,
    },
    {
      commandNumber: 30,
      date: "2023-11-30",
      totalAmount: 13,
      status: "Terminé",
      customer: { lastNameCustomer: "Elderfield", firstNameCustomer: "Elly" },
      articles: {
        name: "ClearBridge Dividend Strategy ESG ETF",
        price: 42,
        qrCode: "45737-221",
        numberOfArticles: 2,
      },
      deliverer: {
        lastNameDeliverer: "Scourfield",
        firstNameDeliverer: "Dolley",
      },
      address: {
        street: "0 Redwing Hill",
        streetNumber: "251",
        postalCode: "1050",
        city: "Bruxelles",
        country: "Belgium",
      },
      is_checked: false,
    },
    {
      commandNumber: 31,
      date: "2023-08-06",
      totalAmount: 9,
      status: "Terminé",
      customer: { lastNameCustomer: "Marti", firstNameCustomer: "Annis" },
      articles: {
        name: "Farmer Brothers Company",
        price: 73,
        qrCode: "54868-5816",
        numberOfArticles: 3,
      },
      deliverer: {
        lastNameDeliverer: "McKinie",
        firstNameDeliverer: "Constantia",
      },
      address: {
        street: "0310 Moulton Terrace",
        streetNumber: "8011",
        postalCode: "7504",
        city: "Tournai",
        country: "Belgium",
      },
      is_checked: false,
    },
    {
      commandNumber: 32,
      date: "2023-04-26",
      totalAmount: 23,
      status: "Terminé",
      customer: { lastNameCustomer: "Scandrick", firstNameCustomer: "Sandy" },
      articles: {
        name: "Bioptix, Inc",
        price: 36,
        qrCode: "59779-259",
        numberOfArticles: 1,
      },
      deliverer: { lastNameDeliverer: "Vasilkov", firstNameDeliverer: "Rice" },
      address: {
        street: "782 Mariners Cove Alley",
        streetNumber: "08",
        postalCode: "1170",
        city: "Bruxelles",
        country: "Belgium",
      },
      is_checked: false,
    },
    {
      commandNumber: 33,
      date: "2023-12-18",
      totalAmount: 64,
      status: "Terminé",
      customer: { lastNameCustomer: "Schoolcroft", firstNameCustomer: "Drugi" },
      articles: {
        name: "CoreSite Realty Corporation",
        price: 55,
        qrCode: "68645-272",
        numberOfArticles: 2,
      },
      deliverer: {
        lastNameDeliverer: "Sharpe",
        firstNameDeliverer: "Marjorie",
      },
      address: {
        street: "9 Little Fleur Point",
        streetNumber: "02272",
        postalCode: "9404",
        city: "Ninove",
        country: "Belgium",
      },
      is_checked: false,
    },
    {
      commandNumber: 34,
      date: "2023-08-20",
      totalAmount: 48,
      status: "Terminé",
      customer: { lastNameCustomer: "Grimme", firstNameCustomer: "Fee" },
      articles: {
        name: "Pingtan Marine Enterprise Ltd.",
        price: 29,
        qrCode: "0113-0605",
        numberOfArticles: 1,
      },
      deliverer: { lastNameDeliverer: "Lynds", firstNameDeliverer: "Manon" },
      address: {
        street: "179 Scofield Road",
        streetNumber: "7521",
        postalCode: "6042",
        city: "Charleroi",
        country: "Belgium",
      },
      is_checked: false,
    },
    {
      commandNumber: 35,
      date: "2023-05-23",
      totalAmount: 89,
      status: "Terminé",
      customer: { lastNameCustomer: "Lamborn", firstNameCustomer: "Jordon" },
      articles: {
        name: "Bank of America Corporation",
        price: 56,
        qrCode: "49288-9935",
        numberOfArticles: 1,
      },
      deliverer: { lastNameDeliverer: "Pettus", firstNameDeliverer: "Winona" },
      address: {
        street: "26431 Buhler Point",
        streetNumber: "4934",
        postalCode: "7032",
        city: "Mons",
        country: "Belgium",
      },
      is_checked: false,
    },
    {
      commandNumber: 36,
      date: "2023-05-03",
      totalAmount: 95,
      status: "Terminé",
      customer: { lastNameCustomer: "Whiteley", firstNameCustomer: "Evaleen" },
      articles: {
        name: "iStar Financial Inc.",
        price: 30,
        qrCode: "41163-403",
        numberOfArticles: 5,
      },
      deliverer: { lastNameDeliverer: "Babst", firstNameDeliverer: "Leela" },
      address: {
        street: "77 Sage Point",
        streetNumber: "83",
        postalCode: "9404",
        city: "Ninove",
        country: "Belgium",
      },
      is_checked: false,
    },
    {
      commandNumber: 37,
      date: "2023-07-01",
      totalAmount: 50,
      status: "Terminé",
      customer: { lastNameCustomer: "Swate", firstNameCustomer: "Rudolph" },
      articles: {
        name: "Global Medical REIT Inc.",
        price: 44,
        qrCode: "33261-844",
        numberOfArticles: 5,
      },
      deliverer: { lastNameDeliverer: "Unitt", firstNameDeliverer: "Noella" },
      address: {
        street: "8754 Michigan Point",
        streetNumber: "3",
        postalCode: "7604",
        city: "Péruwelz",
        country: "Belgium",
      },
      is_checked: false,
    },
    {
      commandNumber: 38,
      date: "2023-10-08",
      totalAmount: 95,
      status: "Terminé",
      customer: { lastNameCustomer: "Broseman", firstNameCustomer: "Leda" },
      articles: {
        name: "The Hackett Group, Inc.",
        price: 78,
        qrCode: "63629-1740",
        numberOfArticles: 1,
      },
      deliverer: { lastNameDeliverer: "Arnout", firstNameDeliverer: "Dotti" },
      address: {
        street: "1352 Ohio Way",
        streetNumber: "64783",
        postalCode: "9404",
        city: "Ninove",
        country: "Belgium",
      },
      is_checked: false,
    },
    {
      commandNumber: 39,
      date: "2023-11-29",
      totalAmount: 99,
      status: "Terminé",
      customer: { lastNameCustomer: "OIlier", firstNameCustomer: "Florette" },
      articles: {
        name: "Sohu.com Inc.",
        price: 49,
        qrCode: "0225-0495",
        numberOfArticles: 4,
      },
      deliverer: {
        lastNameDeliverer: "Dumbar",
        firstNameDeliverer: "Gardiner",
      },
      address: {
        street: "82 Gina Junction",
        streetNumber: "86",
        postalCode: "1170",
        city: "Bruxelles",
        country: "Belgium",
      },
      is_checked: false,
    },
    {
      commandNumber: 40,
      date: "2024-01-28",
      totalAmount: 37,
      status: "Terminé",
      customer: { lastNameCustomer: "Iacomelli", firstNameCustomer: "Rochell" },
      articles: {
        name: "Seagate Technology PLC",
        price: 51,
        qrCode: "64117-182",
        numberOfArticles: 1,
      },
      deliverer: { lastNameDeliverer: "Firmin", firstNameDeliverer: "Thayne" },
      address: {
        street: "32 Utah Junction",
        streetNumber: "014",
        postalCode: "7823",
        city: "Ath",
        country: "Belgium",
      },
      is_checked: false,
    },
    {
      commandNumber: 41,
      date: "2024-01-20",
      totalAmount: 51,
      status: "Terminé",
      customer: { lastNameCustomer: "Eichmann", firstNameCustomer: "Flinn" },
      articles: {
        name: "Annaly Capital Management Inc",
        price: 14,
        qrCode: "0074-6114",
        numberOfArticles: 1,
      },
      deliverer: {
        lastNameDeliverer: "Whitington",
        firstNameDeliverer: "Tripp",
      },
      address: {
        street: "7852 Maple Wood Pass",
        streetNumber: "0",
        postalCode: "2170",
        city: "Antwerpen",
        country: "Belgium",
      },
      is_checked: false,
    },
    {
      commandNumber: 42,
      date: "2023-12-22",
      totalAmount: 74,
      status: "Terminé",
      customer: { lastNameCustomer: "Eickhoff", firstNameCustomer: "Moss" },
      articles: {
        name: "Weingarten Realty Investors",
        price: 52,
        qrCode: "44206-417",
        numberOfArticles: 2,
      },
      deliverer: { lastNameDeliverer: "Wabey", firstNameDeliverer: "Regen" },
      address: {
        street: "7 Northport Trail",
        streetNumber: "381",
        postalCode: "7504",
        city: "Tournai",
        country: "Belgium",
      },
      is_checked: false,
    },
    {
      commandNumber: 43,
      date: "2023-09-22",
      totalAmount: 51,
      status: "Terminé",
      customer: { lastNameCustomer: "Trim", firstNameCustomer: "Damian" },
      articles: {
        name: "Cyclacel Pharmaceuticals, Inc.",
        price: 36,
        qrCode: "36987-3334",
        numberOfArticles: 1,
      },
      deliverer: { lastNameDeliverer: "Ferroni", firstNameDeliverer: "Dory" },
      address: {
        street: "1569 Anthes Alley",
        streetNumber: "7147",
        postalCode: "7536",
        city: "Tournai",
        country: "Belgium",
      },
      is_checked: false,
    },
    {
      commandNumber: 44,
      date: "2023-08-23",
      totalAmount: 70,
      status: "Terminé",
      customer: { lastNameCustomer: "Sextie", firstNameCustomer: "Mavra" },
      articles: {
        name: "Badger Meter, Inc.",
        price: 66,
        qrCode: "68645-341",
        numberOfArticles: 4,
      },
      deliverer: { lastNameDeliverer: "Ewbach", firstNameDeliverer: "Paxon" },
      address: {
        street: "69 Donald Court",
        streetNumber: "6",
        postalCode: "7604",
        city: "Péruwelz",
        country: "Belgium",
      },
      is_checked: false,
    },
    {
      commandNumber: 45,
      date: "2024-03-09",
      totalAmount: 63,
      status: "Terminé",
      customer: { lastNameCustomer: "Orcott", firstNameCustomer: "Baudoin" },
      articles: {
        name: "SJW Group",
        price: 69,
        qrCode: "37000-109",
        numberOfArticles: 4,
      },
      deliverer: {
        lastNameDeliverer: "Alner",
        firstNameDeliverer: "Laurianne",
      },
      address: {
        street: "67672 Claremont Alley",
        streetNumber: "1005",
        postalCode: "7536",
        city: "Tournai",
        country: "Belgium",
      },
      is_checked: false,
    },
    {
      commandNumber: 46,
      date: "2023-10-16",
      totalAmount: 53,
      status: "Terminé",
      customer: { lastNameCustomer: "Ramsbotham", firstNameCustomer: "Vallie" },
      articles: {
        name: "Genco Shipping & Trading Limited Warrants Expiring 12/31/2021 ",
        price: 84,
        qrCode: "35418-119",
        numberOfArticles: 5,
      },
      deliverer: { lastNameDeliverer: "Thomasen", firstNameDeliverer: "Gipsy" },
      address: {
        street: "64 Clemons Center",
        streetNumber: "5",
        postalCode: "6834",
        city: "Bouillon",
        country: "Belgium",
      },
      is_checked: false,
    },
    {
      commandNumber: 47,
      date: "2023-09-29",
      totalAmount: 16,
      status: "Terminé",
      customer: { lastNameCustomer: "Clewlow", firstNameCustomer: "Blake" },
      articles: {
        name: "Verizon Communications Inc.",
        price: 58,
        qrCode: "51655-362",
        numberOfArticles: 5,
      },
      deliverer: { lastNameDeliverer: "Leil", firstNameDeliverer: "Hoebart" },
      address: {
        street: "8425 Cordelia Way",
        streetNumber: "8",
        postalCode: "7823",
        city: "Ath",
        country: "Belgium",
      },
      is_checked: false,
    },
    {
      commandNumber: 48,
      date: "2023-08-28",
      totalAmount: 31,
      status: "Terminé",
      customer: { lastNameCustomer: "Jumonet", firstNameCustomer: "Emmalynn" },
      articles: {
        name: "ICU Medical, Inc.",
        price: 95,
        qrCode: "41167-0942",
        numberOfArticles: 5,
      },
      deliverer: { lastNameDeliverer: "Sillick", firstNameDeliverer: "Janeta" },
      address: {
        street: "48 Linden Way",
        streetNumber: "3",
        postalCode: "7536",
        city: "Tournai",
        country: "Belgium",
      },
      is_checked: false,
    },
    {
      commandNumber: 49,
      date: "2024-02-12",
      totalAmount: 91,
      status: "Terminé",
      customer: { lastNameCustomer: "Allner", firstNameCustomer: "Shandie" },
      articles: {
        name: "PBF Energy Inc.",
        price: 33,
        qrCode: "37000-697",
        numberOfArticles: 3,
      },
      deliverer: {
        lastNameDeliverer: "Kamiyama",
        firstNameDeliverer: "Hadlee",
      },
      address: {
        street: "74 Roxbury Park",
        streetNumber: "946",
        postalCode: "7823",
        city: "Ath",
        country: "Belgium",
      },
      is_checked: false,
    },
    {
      commandNumber: 50,
      date: "2023-10-21",
      totalAmount: 95,
      status: "Terminé",
      customer: { lastNameCustomer: "Blare", firstNameCustomer: "Lois" },
      articles: {
        name: "Wells Fargo & Company",
        price: 57,
        qrCode: "31722-222",
        numberOfArticles: 4,
      },
      deliverer: {
        lastNameDeliverer: "Gawthorpe",
        firstNameDeliverer: "Tamera",
      },
      address: {
        street: "77272 Mayer Center",
        streetNumber: "33",
        postalCode: "7604",
        city: "Péruwelz",
        country: "Belgium",
      },
      is_checked: false,
    },
    {
      commandNumber: 51,
      date: "2023-06-17",
      totalAmount: 69,
      status: "Terminé",
      customer: { lastNameCustomer: "Ellson", firstNameCustomer: "Gustavus" },
      articles: {
        name: "BlackRock 2022 Global Income Opportunity Trust",
        price: 60,
        qrCode: "63187-070",
        numberOfArticles: 2,
      },
      deliverer: {
        lastNameDeliverer: "Schimank",
        firstNameDeliverer: "Ysabel",
      },
      address: {
        street: "08814 Melrose Avenue",
        streetNumber: "45426",
        postalCode: "1050",
        city: "Bruxelles",
        country: "Belgium",
      },
      is_checked: false,
    },
    {
      commandNumber: 52,
      date: "2023-11-07",
      totalAmount: 24,
      status: "Terminé",
      customer: { lastNameCustomer: "Lusher", firstNameCustomer: "Randell" },
      articles: {
        name: "Dril-Quip, Inc.",
        price: 14,
        qrCode: "17312-020",
        numberOfArticles: 3,
      },
      deliverer: { lastNameDeliverer: "Lintott", firstNameDeliverer: "Alley" },
      address: {
        street: "2036 Rutledge Place",
        streetNumber: "8",
        postalCode: "9052",
        city: "Gent",
        country: "Belgium",
      },
      is_checked: false,
    },
    {
      commandNumber: 53,
      date: "2023-04-08",
      totalAmount: 86,
      status: "Terminé",
      customer: { lastNameCustomer: "Arundel", firstNameCustomer: "Vasily" },
      articles: {
        name: "ON Semiconductor Corporation",
        price: 85,
        qrCode: "11527-069",
        numberOfArticles: 2,
      },
      deliverer: {
        lastNameDeliverer: "Corradeschi",
        firstNameDeliverer: "Aaron",
      },
      address: {
        street: "3723 Fulton Parkway",
        streetNumber: "945",
        postalCode: "7604",
        city: "Péruwelz",
        country: "Belgium",
      },
      is_checked: false,
    },
    {
      commandNumber: 54,
      date: "2023-09-29",
      totalAmount: 97,
      status: "Terminé",
      customer: { lastNameCustomer: "Alesio", firstNameCustomer: "Faber" },
      articles: {
        name: "Novanta Inc.",
        price: 96,
        qrCode: "54868-3269",
        numberOfArticles: 1,
      },
      deliverer: { lastNameDeliverer: "Scarse", firstNameDeliverer: "Chevy" },
      address: {
        street: "0830 Crowley Drive",
        streetNumber: "8688",
        postalCode: "6594",
        city: "Momignies",
        country: "Belgium",
      },
      is_checked: false,
    },
    {
      commandNumber: 55,
      date: "2023-05-13",
      totalAmount: 66,
      status: "Terminé",
      customer: { lastNameCustomer: "Crosse", firstNameCustomer: "Korey" },
      articles: {
        name: "Laredo Petroleum, Inc.",
        price: 39,
        qrCode: "0228-2597",
        numberOfArticles: 2,
      },
      deliverer: { lastNameDeliverer: "Burress", firstNameDeliverer: "Phoebe" },
      address: {
        street: "956 Reinke Avenue",
        streetNumber: "59885",
        postalCode: "7604",
        city: "Péruwelz",
        country: "Belgium",
      },
      is_checked: false,
    },
    {
      commandNumber: 56,
      date: "2023-04-26",
      totalAmount: 36,
      status: "Terminé",
      customer: { lastNameCustomer: "Jerke", firstNameCustomer: "Mureil" },
      articles: {
        name: "Brocade Communications Systems, Inc.",
        price: 44,
        qrCode: "15127-863",
        numberOfArticles: 5,
      },
      deliverer: {
        lastNameDeliverer: "Harroway",
        firstNameDeliverer: "Faythe",
      },
      address: {
        street: "00 Ohio Parkway",
        streetNumber: "43206",
        postalCode: "7536",
        city: "Tournai",
        country: "Belgium",
      },
      is_checked: false,
    },
    {
      commandNumber: 57,
      date: "2023-09-24",
      totalAmount: 37,
      status: "Terminé",
      customer: { lastNameCustomer: "Ovington", firstNameCustomer: "Dorella" },
      articles: {
        name: "Canadian National Railway Company",
        price: 10,
        qrCode: "0703-4636",
        numberOfArticles: 3,
      },
      deliverer: { lastNameDeliverer: "Podd", firstNameDeliverer: "Cami" },
      address: {
        street: "66704 Hoard Point",
        streetNumber: "8",
        postalCode: "9404",
        city: "Ninove",
        country: "Belgium",
      },
      is_checked: false,
    },
    {
      commandNumber: 58,
      date: "2024-02-08",
      totalAmount: 58,
      status: "Terminé",
      customer: { lastNameCustomer: "Grocutt", firstNameCustomer: "Maddi" },
      articles: {
        name: "Invesco Credit Opportunities Fund",
        price: 17,
        qrCode: "50436-6590",
        numberOfArticles: 2,
      },
      deliverer: { lastNameDeliverer: "Cham", firstNameDeliverer: "Ninette" },
      address: {
        street: "537 Gerald Lane",
        streetNumber: "5",
        postalCode: "6594",
        city: "Momignies",
        country: "Belgium",
      },
      is_checked: false,
    },
    {
      commandNumber: 59,
      date: "2024-02-01",
      totalAmount: 7,
      status: "Terminé",
      customer: { lastNameCustomer: "Mence", firstNameCustomer: "Farley" },
      articles: {
        name: "Nustar Energy L.P.",
        price: 22,
        qrCode: "68405-027",
        numberOfArticles: 5,
      },
      deliverer: { lastNameDeliverer: "Obey", firstNameDeliverer: "Chicky" },
      address: {
        street: "23969 Loeprich Court",
        streetNumber: "21",
        postalCode: "7032",
        city: "Mons",
        country: "Belgium",
      },
      is_checked: false,
    },
    {
      commandNumber: 60,
      date: "2023-04-10",
      totalAmount: 83,
      status: "Terminé",
      customer: { lastNameCustomer: "Coleford", firstNameCustomer: "Rozella" },
      articles: {
        name: "Citizens, Inc.",
        price: 6,
        qrCode: "57520-0178",
        numberOfArticles: 3,
      },
      deliverer: {
        lastNameDeliverer: "Norbury",
        firstNameDeliverer: "Andromache",
      },
      address: {
        street: "254 Maywood Center",
        streetNumber: "609",
        postalCode: "5100",
        city: "Namur",
        country: "Belgium",
      },
      is_checked: false,
    },
    {
      commandNumber: 61,
      date: "2023-04-04",
      totalAmount: 9,
      status: "Terminé",
      customer: { lastNameCustomer: "Jarad", firstNameCustomer: "Raimundo" },
      articles: {
        name: "Farmers National Banc Corp.",
        price: 16,
        qrCode: "64305-007",
        numberOfArticles: 5,
      },
      deliverer: { lastNameDeliverer: "Jime", firstNameDeliverer: "Hakeem" },
      address: {
        street: "3572 Manufacturers Pass",
        streetNumber: "333",
        postalCode: "6042",
        city: "Charleroi",
        country: "Belgium",
      },
      is_checked: false,
    },
    {
      commandNumber: 62,
      date: "2023-07-10",
      totalAmount: 14,
      status: "Terminé",
      customer: { lastNameCustomer: "Fredi", firstNameCustomer: "Lucio" },
      articles: {
        name: "Eagle Bancorp Montana, Inc.",
        price: 7,
        qrCode: "44567-707",
        numberOfArticles: 2,
      },
      deliverer: { lastNameDeliverer: "Kielt", firstNameDeliverer: "Angela" },
      address: {
        street: "5 Myrtle Park",
        streetNumber: "98467",
        postalCode: "5100",
        city: "Namur",
        country: "Belgium",
      },
      is_checked: false,
    },
    {
      commandNumber: 63,
      date: "2023-08-01",
      totalAmount: 18,
      status: "Terminé",
      customer: { lastNameCustomer: "Ladel", firstNameCustomer: "Gonzales" },
      articles: {
        name: "First Trust BICK Index Fund",
        price: 37,
        qrCode: "49999-905",
        numberOfArticles: 3,
      },
      deliverer: { lastNameDeliverer: "Hagland", firstNameDeliverer: "Alexi" },
      address: {
        street: "376 Cordelia Center",
        streetNumber: "4",
        postalCode: "7536",
        city: "Tournai",
        country: "Belgium",
      },
      is_checked: false,
    },
    {
      commandNumber: 64,
      date: "2023-11-19",
      totalAmount: 77,
      status: "Terminé",
      customer: { lastNameCustomer: "Pallent", firstNameCustomer: "Cassi" },
      articles: {
        name: "Twitter, Inc.",
        price: 13,
        qrCode: "30142-238",
        numberOfArticles: 3,
      },
      deliverer: {
        lastNameDeliverer: "Varns",
        firstNameDeliverer: "Celestina",
      },
      address: {
        street: "8 Michigan Junction",
        streetNumber: "03569",
        postalCode: "6042",
        city: "Charleroi",
        country: "Belgium",
      },
      is_checked: false,
    },
    {
      commandNumber: 65,
      date: "2023-05-30",
      totalAmount: 66,
      status: "Terminé",
      customer: { lastNameCustomer: "Roma", firstNameCustomer: "Mercie" },
      articles: {
        name: "Group 1 Automotive, Inc.",
        price: 66,
        qrCode: "64893-300",
        numberOfArticles: 1,
      },
      deliverer: { lastNameDeliverer: "Jedrych", firstNameDeliverer: "Lanny" },
      address: {
        street: "2753 Swallow Lane",
        streetNumber: "35127",
        postalCode: "9052",
        city: "Gent",
        country: "Belgium",
      },
      is_checked: false,
    },
    {
      commandNumber: 66,
      date: "2023-06-15",
      totalAmount: 64,
      status: "Terminé",
      customer: { lastNameCustomer: "Beacock", firstNameCustomer: "Bryanty" },
      articles: {
        name: "Owens-Illinois, Inc.",
        price: 45,
        qrCode: "68180-281",
        numberOfArticles: 4,
      },
      deliverer: { lastNameDeliverer: "Mathivat", firstNameDeliverer: "York" },
      address: {
        street: "45234 Helena Road",
        streetNumber: "7",
        postalCode: "6594",
        city: "Momignies",
        country: "Belgium",
      },
      is_checked: false,
    },
    {
      commandNumber: 67,
      date: "2023-09-20",
      totalAmount: 31,
      status: "Terminé",
      customer: { lastNameCustomer: "Copper", firstNameCustomer: "Anselma" },
      articles: {
        name: "FelCor Lodging Trust Incorporated",
        price: 2,
        qrCode: "49999-291",
        numberOfArticles: 5,
      },
      deliverer: {
        lastNameDeliverer: "Cullinan",
        firstNameDeliverer: "Samuel",
      },
      address: {
        street: "899 Heath Pass",
        streetNumber: "0",
        postalCode: "1050",
        city: "Bruxelles",
        country: "Belgium",
      },
      is_checked: false,
    },
    {
      commandNumber: 68,
      date: "2023-05-13",
      totalAmount: 87,
      status: "Terminé",
      customer: { lastNameCustomer: "Thomassen", firstNameCustomer: "Joline" },
      articles: {
        name: "Arch Capital Group Ltd.",
        price: 25,
        qrCode: "17575-190",
        numberOfArticles: 2,
      },
      deliverer: { lastNameDeliverer: "Pohlak", firstNameDeliverer: "Naomi" },
      address: {
        street: "4263 Burning Wood Parkway",
        streetNumber: "0",
        postalCode: "1050",
        city: "Bruxelles",
        country: "Belgium",
      },
      is_checked: false,
    },
    {
      commandNumber: 69,
      date: "2023-10-27",
      totalAmount: 85,
      status: "Terminé",
      customer: { lastNameCustomer: "Lasselle", firstNameCustomer: "Lemmie" },
      articles: {
        name: "Embotelladora Andina S.A.",
        price: 77,
        qrCode: "0378-8171",
        numberOfArticles: 5,
      },
      deliverer: { lastNameDeliverer: "Blevin", firstNameDeliverer: "Syd" },
      address: {
        street: "036 Arapahoe Plaza",
        streetNumber: "23",
        postalCode: "1050",
        city: "Bruxelles",
        country: "Belgium",
      },
      is_checked: false,
    },
    {
      commandNumber: 70,
      date: "2023-09-21",
      totalAmount: 19,
      status: "Terminé",
      customer: { lastNameCustomer: "Twelve", firstNameCustomer: "Shel" },
      articles: {
        name: "Vina Concha Y Toro",
        price: 21,
        qrCode: "0113-0588",
        numberOfArticles: 5,
      },
      deliverer: { lastNameDeliverer: "Probat", firstNameDeliverer: "Shirl" },
      address: {
        street: "3 Stone Corner Terrace",
        streetNumber: "990",
        postalCode: "9052",
        city: "Gent",
        country: "Belgium",
      },
      is_checked: false,
    },
    {
      commandNumber: 71,
      date: "2023-10-28",
      totalAmount: 38,
      status: "Terminé",
      customer: {
        lastNameCustomer: "Brooking",
        firstNameCustomer: "Mariellen",
      },
      articles: {
        name: "VTTI Energy Partners LP",
        price: 13,
        qrCode: "0955-1035",
        numberOfArticles: 5,
      },
      deliverer: {
        lastNameDeliverer: "Harrower",
        firstNameDeliverer: "Harmonie",
      },
      address: {
        street: "9527 Lakewood Gardens Alley",
        streetNumber: "4935",
        postalCode: "9052",
        city: "Gent",
        country: "Belgium",
      },
      is_checked: false,
    },
    {
      commandNumber: 72,
      date: "2024-02-24",
      totalAmount: 58,
      status: "Terminé",
      customer: { lastNameCustomer: "Meake", firstNameCustomer: "Thaddeus" },
      articles: {
        name: "Apollo Global Management, LLC",
        price: 2,
        qrCode: "49852-014",
        numberOfArticles: 3,
      },
      deliverer: { lastNameDeliverer: "Kaspar", firstNameDeliverer: "Auberta" },
      address: {
        street: "746 Mosinee Lane",
        streetNumber: "27",
        postalCode: "1170",
        city: "Bruxelles",
        country: "Belgium",
      },
      is_checked: false,
    },
    {
      commandNumber: 73,
      date: "2023-04-09",
      totalAmount: 63,
      status: "Terminé",
      customer: { lastNameCustomer: "Nehl", firstNameCustomer: "Jamey" },
      articles: {
        name: "Amedisys Inc",
        price: 30,
        qrCode: "0268-0904",
        numberOfArticles: 5,
      },
      deliverer: {
        lastNameDeliverer: "Harradine",
        firstNameDeliverer: "Gabrielle",
      },
      address: {
        street: "8 Johnson Lane",
        streetNumber: "1",
        postalCode: "7823",
        city: "Ath",
        country: "Belgium",
      },
      is_checked: false,
    },
    {
      commandNumber: 74,
      date: "2023-05-14",
      totalAmount: 44,
      status: "Terminé",
      customer: { lastNameCustomer: "Elsmore", firstNameCustomer: "Lilla" },
      articles: {
        name: "BlackRock Income Trust Inc. (The)",
        price: 71,
        qrCode: "14290-283",
        numberOfArticles: 4,
      },
      deliverer: { lastNameDeliverer: "Blick", firstNameDeliverer: "Frank" },
      address: {
        street: "29 Crownhardt Trail",
        streetNumber: "13",
        postalCode: "9404",
        city: "Ninove",
        country: "Belgium",
      },
      is_checked: false,
    },
    {
      commandNumber: 75,
      date: "2023-06-08",
      totalAmount: 23,
      status: "Terminé",
      customer: { lastNameCustomer: "Lavis", firstNameCustomer: "Emile" },
      articles: {
        name: "Discover Financial Services",
        price: 14,
        qrCode: "55926-0021",
        numberOfArticles: 5,
      },
      deliverer: {
        lastNameDeliverer: "Mortell",
        firstNameDeliverer: "Dominic",
      },
      address: {
        street: "81737 Holmberg Avenue",
        streetNumber: "13",
        postalCode: "2170",
        city: "Antwerpen",
        country: "Belgium",
      },
      is_checked: false,
    },
    {
      commandNumber: 76,
      date: "2023-11-08",
      totalAmount: 75,
      status: "Terminé",
      customer: { lastNameCustomer: "Arlow", firstNameCustomer: "Suzann" },
      articles: {
        name: "Oppenheimer Holdings, Inc.",
        price: 14,
        qrCode: "52686-331",
        numberOfArticles: 5,
      },
      deliverer: { lastNameDeliverer: "Feavyour", firstNameDeliverer: "Mona" },
      address: {
        street: "87 Meadow Vale Avenue",
        streetNumber: "69676",
        postalCode: "7504",
        city: "Tournai",
        country: "Belgium",
      },
      is_checked: false,
    },
    {
      commandNumber: 77,
      date: "2023-08-16",
      totalAmount: 68,
      status: "Terminé",
      customer: { lastNameCustomer: "Jannex", firstNameCustomer: "Norris" },
      articles: {
        name: "Semiconductor  Manufacturing International Corporation",
        price: 10,
        qrCode: "37000-615",
        numberOfArticles: 2,
      },
      deliverer: { lastNameDeliverer: "Wevell", firstNameDeliverer: "Oralia" },
      address: {
        street: "466 Blaine Center",
        streetNumber: "9",
        postalCode: "6042",
        city: "Charleroi",
        country: "Belgium",
      },
      is_checked: false,
    },
    {
      commandNumber: 78,
      date: "2023-05-14",
      totalAmount: 45,
      status: "Terminé",
      customer: { lastNameCustomer: "Scougall", firstNameCustomer: "Lezlie" },
      articles: {
        name: "CAE Inc",
        price: 20,
        qrCode: "68258-6044",
        numberOfArticles: 1,
      },
      deliverer: {
        lastNameDeliverer: "Goodier",
        firstNameDeliverer: "Papagena",
      },
      address: {
        street: "957 Surrey Road",
        streetNumber: "4",
        postalCode: "7504",
        city: "Tournai",
        country: "Belgium",
      },
      is_checked: false,
    },
    {
      commandNumber: 79,
      date: "2023-05-19",
      totalAmount: 78,
      status: "Terminé",
      customer: { lastNameCustomer: "Grattage", firstNameCustomer: "Ruthi" },
      articles: {
        name: "Applied DNA Sciences Inc",
        price: 82,
        qrCode: "10139-070",
        numberOfArticles: 3,
      },
      deliverer: {
        lastNameDeliverer: "Damiata",
        firstNameDeliverer: "Kimberly",
      },
      address: {
        street: "77968 Haas Road",
        streetNumber: "26",
        postalCode: "6042",
        city: "Charleroi",
        country: "Belgium",
      },
      is_checked: false,
    },
    {
      commandNumber: 80,
      date: "2024-02-02",
      totalAmount: 11,
      status: "Terminé",
      customer: { lastNameCustomer: "Potbury", firstNameCustomer: "Jaquelyn" },
      articles: {
        name: "Orbotech Ltd.",
        price: 58,
        qrCode: "37000-116",
        numberOfArticles: 3,
      },
      deliverer: { lastNameDeliverer: "Rummin", firstNameDeliverer: "Ralf" },
      address: {
        street: "41 Holy Cross Road",
        streetNumber: "87865",
        postalCode: "9052",
        city: "Gent",
        country: "Belgium",
      },
      is_checked: false,
    },
    {
      commandNumber: 81,
      date: "2024-02-21",
      totalAmount: 92,
      status: "Terminé",
      customer: { lastNameCustomer: "Francescozzi", firstNameCustomer: "Jo" },
      articles: {
        name: "CTI Industries Corporation",
        price: 97,
        qrCode: "0409-4090",
        numberOfArticles: 2,
      },
      deliverer: {
        lastNameDeliverer: "Beverage",
        firstNameDeliverer: "Daphene",
      },
      address: {
        street: "3017 Hooker Point",
        streetNumber: "8705",
        postalCode: "6834",
        city: "Bouillon",
        country: "Belgium",
      },
      is_checked: false,
    },
    {
      commandNumber: 82,
      date: "2023-09-14",
      totalAmount: 33,
      status: "Terminé",
      customer: { lastNameCustomer: "Harridge", firstNameCustomer: "Ximenes" },
      articles: {
        name: "Investar Holding Corporation",
        price: 34,
        qrCode: "11084-127",
        numberOfArticles: 3,
      },
      deliverer: { lastNameDeliverer: "Lafford", firstNameDeliverer: "Peri" },
      address: {
        street: "8 Crescent Oaks Circle",
        streetNumber: "0",
        postalCode: "6834",
        city: "Bouillon",
        country: "Belgium",
      },
      is_checked: false,
    },
    {
      commandNumber: 83,
      date: "2023-07-17",
      totalAmount: 66,
      status: "Terminé",
      customer: { lastNameCustomer: "Shankle", firstNameCustomer: "Kyrstin" },
      articles: {
        name: "Bob Evans Farms, Inc.",
        price: 87,
        qrCode: "0009-0626",
        numberOfArticles: 5,
      },
      deliverer: { lastNameDeliverer: "Duckett", firstNameDeliverer: "Tally" },
      address: {
        street: "89092 Harper Road",
        streetNumber: "4",
        postalCode: "9404",
        city: "Ninove",
        country: "Belgium",
      },
      is_checked: false,
    },
    {
      commandNumber: 84,
      date: "2023-07-15",
      totalAmount: 48,
      status: "Terminé",
      customer: { lastNameCustomer: "Cridlon", firstNameCustomer: "Lucien" },
      articles: {
        name: "Freeport-McMoran, Inc.",
        price: 38,
        qrCode: "0225-0495",
        numberOfArticles: 1,
      },
      deliverer: { lastNameDeliverer: "Stuke", firstNameDeliverer: "Jackie" },
      address: {
        street: "4 Hanson Avenue",
        streetNumber: "323",
        postalCode: "7032",
        city: "Mons",
        country: "Belgium",
      },
      is_checked: false,
    },
    {
      commandNumber: 85,
      date: "2024-02-29",
      totalAmount: 12,
      status: "Terminé",
      customer: { lastNameCustomer: "Haliday", firstNameCustomer: "Ambrosio" },
      articles: {
        name: "X-Links Silver Shares Covered Call ETN",
        price: 46,
        qrCode: "42507-224",
        numberOfArticles: 1,
      },
      deliverer: { lastNameDeliverer: "Baterip", firstNameDeliverer: "Arnuad" },
      address: {
        street: "90 Schlimgen Way",
        streetNumber: "80",
        postalCode: "7536",
        city: "Tournai",
        country: "Belgium",
      },
      is_checked: false,
    },
    {
      commandNumber: 86,
      date: "2024-02-08",
      totalAmount: 69,
      status: "Terminé",
      customer: { lastNameCustomer: "Stansall", firstNameCustomer: "Virginie" },
      articles: {
        name: "Navios Maritime Acquisition Corporation",
        price: 53,
        qrCode: "21695-127",
        numberOfArticles: 1,
      },
      deliverer: {
        lastNameDeliverer: "Sanbrooke",
        firstNameDeliverer: "Valentia",
      },
      address: {
        street: "26245 Hoffman Pass",
        streetNumber: "681",
        postalCode: "7536",
        city: "Tournai",
        country: "Belgium",
      },
      is_checked: false,
    },
    {
      commandNumber: 87,
      date: "2024-01-07",
      totalAmount: 26,
      status: "Terminé",
      customer: { lastNameCustomer: "Morcomb", firstNameCustomer: "Reese" },
      articles: {
        name: "Salient Midstream & MLP Fund",
        price: 90,
        qrCode: "0078-0599",
        numberOfArticles: 3,
      },
      deliverer: {
        lastNameDeliverer: "Keigher",
        firstNameDeliverer: "Lavinie",
      },
      address: {
        street: "98144 Dennis Plaza",
        streetNumber: "27297",
        postalCode: "7536",
        city: "Tournai",
        country: "Belgium",
      },
      is_checked: false,
    },
    {
      commandNumber: 88,
      date: "2023-12-25",
      totalAmount: 80,
      status: "Terminé",
      customer: { lastNameCustomer: "Coles", firstNameCustomer: "Fernando" },
      articles: {
        name: "Westmoreland Resource Partners, LP",
        price: 65,
        qrCode: "49281-014",
        numberOfArticles: 2,
      },
      deliverer: { lastNameDeliverer: "Roos", firstNameDeliverer: "Hilde" },
      address: {
        street: "11 Warrior Pass",
        streetNumber: "96181",
        postalCode: "5100",
        city: "Namur",
        country: "Belgium",
      },
      is_checked: false,
    },
    {
      commandNumber: 89,
      date: "2023-05-23",
      totalAmount: 47,
      status: "Terminé",
      customer: {
        lastNameCustomer: "Withringten",
        firstNameCustomer: "Marcelline",
      },
      articles: {
        name: "Veracyte, Inc.",
        price: 37,
        qrCode: "50845-0109",
        numberOfArticles: 5,
      },
      deliverer: { lastNameDeliverer: "Gegay", firstNameDeliverer: "Jsandye" },
      address: {
        street: "3 Knutson Crossing",
        streetNumber: "00",
        postalCode: "7032",
        city: "Mons",
        country: "Belgium",
      },
      is_checked: false,
    },
    {
      commandNumber: 90,
      date: "2024-02-05",
      totalAmount: 56,
      status: "Terminé",
      customer: { lastNameCustomer: "Hodgin", firstNameCustomer: "Pamela" },
      articles: {
        name: "First Trust Total US Market AlphaDEX ETF",
        price: 77,
        qrCode: "44523-542",
        numberOfArticles: 4,
      },
      deliverer: { lastNameDeliverer: "Amoss", firstNameDeliverer: "Elmo" },
      address: {
        street: "6 Dawn Park",
        streetNumber: "1561",
        postalCode: "9404",
        city: "Ninove",
        country: "Belgium",
      },
      is_checked: false,
    },
    {
      commandNumber: 91,
      date: "2023-09-08",
      totalAmount: 30,
      status: "Terminé",
      customer: { lastNameCustomer: "Bottomore", firstNameCustomer: "Bunny" },
      articles: {
        name: "Aratana Therapeutics, Inc.",
        price: 94,
        qrCode: "62584-145",
        numberOfArticles: 2,
      },
      deliverer: { lastNameDeliverer: "Coldbath", firstNameDeliverer: "Sean" },
      address: {
        street: "05 Ruskin Plaza",
        streetNumber: "3922",
        postalCode: "9052",
        city: "Gent",
        country: "Belgium",
      },
      is_checked: false,
    },
    {
      commandNumber: 92,
      date: "2023-10-31",
      totalAmount: 6,
      status: "Terminé",
      customer: { lastNameCustomer: "Arbor", firstNameCustomer: "Gino" },
      articles: {
        name: "Gencor Industries Inc.",
        price: 88,
        qrCode: "49035-580",
        numberOfArticles: 2,
      },
      deliverer: { lastNameDeliverer: "Guntrip", firstNameDeliverer: "Dal" },
      address: {
        street: "714 Sunbrook Lane",
        streetNumber: "742",
        postalCode: "6594",
        city: "Momignies",
        country: "Belgium",
      },
      is_checked: false,
    },
    {
      commandNumber: 93,
      date: "2023-12-16",
      totalAmount: 64,
      status: "Terminé",
      customer: {
        lastNameCustomer: "Blackaller",
        firstNameCustomer: "Devondra",
      },
      articles: {
        name: "NextEra Energy, Inc.",
        price: 59,
        qrCode: "40076-949",
        numberOfArticles: 2,
      },
      deliverer: { lastNameDeliverer: "Eathorne", firstNameDeliverer: "Paola" },
      address: {
        street: "9848 Trailsway Center",
        streetNumber: "31084",
        postalCode: "9404",
        city: "Ninove",
        country: "Belgium",
      },
      is_checked: false,
    },
    {
      commandNumber: 94,
      date: "2024-03-03",
      totalAmount: 47,
      status: "Terminé",
      customer: { lastNameCustomer: "Thiese", firstNameCustomer: "Grace" },
      articles: {
        name: "Gaming Partners International Corporation",
        price: 23,
        qrCode: "55154-0876",
        numberOfArticles: 4,
      },
      deliverer: { lastNameDeliverer: "Wibrow", firstNameDeliverer: "Deane" },
      address: {
        street: "1573 Esch Road",
        streetNumber: "0144",
        postalCode: "6594",
        city: "Momignies",
        country: "Belgium",
      },
      is_checked: false,
    },
    {
      commandNumber: 95,
      date: "2023-12-13",
      totalAmount: 71,
      status: "Terminé",
      customer: { lastNameCustomer: "Crose", firstNameCustomer: "Wilfrid" },
      articles: {
        name: "Hillenbrand Inc",
        price: 33,
        qrCode: "30142-601",
        numberOfArticles: 1,
      },
      deliverer: {
        lastNameDeliverer: "Oakton",
        firstNameDeliverer: "Ludovika",
      },
      address: {
        street: "280 Clemons Park",
        streetNumber: "39",
        postalCode: "9052",
        city: "Gent",
        country: "Belgium",
      },
      is_checked: false,
    },
    {
      commandNumber: 96,
      date: "2023-08-09",
      totalAmount: 53,
      status: "Terminé",
      customer: { lastNameCustomer: "Huguet", firstNameCustomer: "Hermina" },
      articles: {
        name: "Glatfelter",
        price: 60,
        qrCode: "68001-176",
        numberOfArticles: 3,
      },
      deliverer: {
        lastNameDeliverer: "Minshull",
        firstNameDeliverer: "Annabela",
      },
      address: {
        street: "1 Dorton Avenue",
        streetNumber: "9931",
        postalCode: "1170",
        city: "Bruxelles",
        country: "Belgium",
      },
      is_checked: false,
    },
    {
      commandNumber: 97,
      date: "2024-02-04",
      totalAmount: 22,
      status: "Terminé",
      customer: { lastNameCustomer: "Presdie", firstNameCustomer: "Caddric" },
      articles: {
        name: "Flushing Financial Corporation",
        price: 40,
        qrCode: "76237-133",
        numberOfArticles: 2,
      },
      deliverer: { lastNameDeliverer: "Blythe", firstNameDeliverer: "Kata" },
      address: {
        street: "8369 Crowley Lane",
        streetNumber: "68456",
        postalCode: "7823",
        city: "Ath",
        country: "Belgium",
      },
      is_checked: false,
    },
    {
      commandNumber: 98,
      date: "2024-03-27",
      totalAmount: 10,
      status: "Terminé",
      customer: { lastNameCustomer: "Doerffer", firstNameCustomer: "Hayley" },
      articles: {
        name: "Cohen & Steers Inc",
        price: 44,
        qrCode: "65862-287",
        numberOfArticles: 5,
      },
      deliverer: {
        lastNameDeliverer: "Kirman",
        firstNameDeliverer: "Sutherlan",
      },
      address: {
        street: "989 Mcbride Junction",
        streetNumber: "21",
        postalCode: "7536",
        city: "Tournai",
        country: "Belgium",
      },
      is_checked: false,
    },
    {
      commandNumber: 99,
      date: "2024-02-28",
      totalAmount: 57,
      status: "Terminé",
      customer: { lastNameCustomer: "Boyse", firstNameCustomer: "Carlee" },
      articles: {
        name: "Great Lakes Dredge & Dock Corporation",
        price: 82,
        qrCode: "57344-109",
        numberOfArticles: 4,
      },
      deliverer: {
        lastNameDeliverer: "O' Mahony",
        firstNameDeliverer: "Pierre",
      },
      address: {
        street: "477 Stuart Park",
        streetNumber: "9",
        postalCode: "9404",
        city: "Ninove",
        country: "Belgium",
      },
      is_checked: false,
    },
    {
      commandNumber: 100,
      date: "2023-05-26",
      totalAmount: 11,
      status: "Terminé",
      customer: { lastNameCustomer: "Pack", firstNameCustomer: "Allsun" },
      articles: {
        name: "Six Flags Entertainment Corporation New",
        price: 38,
        qrCode: "50458-330",
        numberOfArticles: 4,
      },
      deliverer: { lastNameDeliverer: "Lumly", firstNameDeliverer: "Terrill" },
      address: {
        street: "2654 Northport Parkway",
        streetNumber: "11030",
        postalCode: "7504",
        city: "Tournai",
        country: "Belgium",
      },
      is_checked: false,
    },
  ];

  return dataTest;
}

export default DataTest;
