function Cities() {
  const cities = [
    "Alost",
    "Anvers",
    "Arlon",
    "Audenarde",
    "Binche",
    "Bruges",
    "Bruxelles",
    "Charleroi",
    "Châtelet",
    "Courtrai",
    "Dendermonde",
    "Diest",
    "Eeklo",
    "Fontaine-l'Évêque",
    "Furnes",
    "Gand",
    "Genappe",
    "Genk",
    "Gistel",
    "Hal",
    "Hamont-Achel",
    "Hasselt",
    "Herck-la-Ville",
    "Herentals",
    "Herstal",
    "Huy",
    "Iseghem",
    "La Louvière",
    "Le Rœulx",
    "Liège",
    "Lierre",
    "Louvain",
    "Marche-en-Famenne",
    "Mons",
    "Namur",
    "Neufchâteau",
    "Nieuport",
    "Nivelles",
    "Ostende",
    "Ottignies-Louvain-la-Neuve",
    "Péruwelz",
    "Philippeville",
    "Rochefort",
    "Roulers",
    "Saint-Ghislain",
    "Saint-Nicolas",
    "Seraing",
    "Soignies",
    "Stavelot",
    "Thuin",
    "Tielt",
    "Tirlemont",
    "Tournai",
    "Turnhout",
    "Verviers",
    "Vilvorde",
    "Visé",
    "Waremme",
    "Wavre",
    "Ypres",
  ];

  return cities;
}

export default Cities;
